language: node_js
node_js:
  - 13.0.1
cache:
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn test
  - yarn build

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local_dir: build
    on:
      branch: master
  - provider: npm
    email: "carlton.joseph@gmail.com"
    api_key: $NPM_TOKEN
    on:
      tags: true
      branch: master

after_success:
  - yarn semanticr
