language: node_js
node_js:
  - 13.0.1
cache: yarn

install:
  - yarn ci

script:
  - yarn test
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: gh-pages
