pipeline {
  agent {
    docker {
      image 'node:13.1.0'
      args '-p 3000:3000'
    }
  }
  environment {
    CI = 'true'
    GIT_BRANCH = 'master'
    GITHUB_TOKEN = credentials('GITHUB_TOKEN')
    NPM_TOKEN = credentials('NPM_TOKEN')
    NPM_EMAIL = credentials('NPM_EMAIL')
    NPM_USERNAME = credentials('NPM_USERNAME')
  }
  stages {
    stage('Install') {
      steps {
        sh 'yarn'
      }
    }
    stage('Test') {
      steps {
        sh 'yarn test'
      }
    }
    stage('Build') {
      steps {
        sh 'yarn build'
      }
    }
    stage('Gh-Pages') {
      steps {
        sh 'git config --global user.email "carlton.joseph@gmail.com"'
        sh 'git config --global user.name "Cartlton Joseph"'
        echo "npm email ${NPM_EMAIL}"
        sh 'yarn gph'
      }
    }
    stage('Deploy') {
      steps {
        sh 'yarn semanticr'
      }
    }
  }
}
