pipeline {
  agent {
    docker {
      image 'node:13.1.0'
      args '-p 3000:3000'
    }
  }
  environment {
    CI = 'true'
    GIT_BRANCH = 'master'
    GITHUB_TOKEN = credentials('GITHUB_TOKEN')
    NPM_TOKEN = credentials('NPM_TOKEN')
    NPM_EMAIL = 'carlton.joseph@gmai.com'
    NPM_USERNAME = 'carltonj2000'
    USERNAME = 'Carlton Joseph'
  }
  stages {
    stage('Install') {
      steps {
        sh 'yarn'
      }
    }
    stage('Test') {
      steps {
        sh 'yarn test'
      }
    }
    stage('Build') {
      steps {
        sh 'yarn build'
      }
    }
    stage('Gh-Pages') {
      steps {
        sh "apt upgrade -y git"
        sh "git config --global user.email \"${NPM_EMAIL}\""
        sh "git config --global user.name \"${USERNAME}\""
        sh "git --version"
        sh 'yarn gph'
      }
    }
    stage('Deploy') {
      steps {
        sh 'yarn semanticr'
      }
    }
  }
}
